
POST http://localhost:8899/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "a123@nnn.com",
  "mobile": "12345609854",
  "firstName" : "someone1",
  "lastName": "Codecamp",
  "password": "123456",
  "confirmPassword": "123456"
}

###

GET http://localhost:8899/api/auth/men HTTP/1.1

###



POST http://localhost:8899/api/auth/login HTTP/1.1

###

POST http://localhost:8899/api/auth/register HTTP/1.1

###

GET http://localhost:8899/api/auth/me HTTP/1.1

###

POST http://localhost:8899/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "identity": "andy@gg.mail",
  "password": "123456"
}

###

POST http://localhost:8899/api/post HTTP/1.1
Content-Type: application/json

{
  "identity": "andy@gg.mail",
  "password": "123456"
}